spring:
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: ${MYSQL_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id

jwt:
  secretKey: "your-secret-key"  # JWT 서명에 사용되는 비밀 키
  access:
    expiration: 3600  # 액세스 토큰 만료 시간(초)
    cookie: "accessToken"  # 액세스 토큰의 쿠키 이름
  refresh:
    expiration: 86400  # 리프레시 토큰 만료 시간(초)
    cookie: "refreshToken"  # 리프레시 토큰의 쿠키 이름
  redirect-uri-user: "http://localhost:3000/user"  # 사용자 리디렉션 URL
